language: ruby

rvm:
- 2.1

branches:
  only:
    - master

before_script: bash ./before.sh

script: "bundle exec jekyll build"

after_success:
  - "REPO=$(basename `git rev-parse --show-toplevel`)"
  - "echo $REPO"
  - "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
  - "echo $TRAVIS_PULL_REQUEST"
  - "USR=`git remote show origin -n | grep h.URL | sed 's/.*\/\/github.com\///;s/.git$//'| cut -d'/' -f1`"
  - "echo $USR"
  - "curl https://api.github.com/repos/$USR/$REPO/pulls/$TRAVIS_PULL_REQUEST"
  - bash ./push.sh
