language: ruby

rvm:
- 2.1

branches:
  only:
    - master

before_script: bash ./before.sh

script: "bundle exec jekyll build"

after_success:
  - "REPO=$(basename `git rev-parse --show-toplevel`)"
  - "choe $REPO"
  - bash ./push.sh
