language: ruby

rvm:
- 2.1

branches:
  only:
    - master

before_script: bash ./before.sh

script: "bundle exec jekyll build"

after_success:
  - "echo TRIGGER_REPO $TRIGGER_REPO"
  - bash ./push.sh
